<Project Sdk="Microsoft.NET.Sdk.Web">
	<!-- We must change the .Net.Sdk to ->> .Net.Sdk.Web because we use the sign in manager in the account services -->
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		<!--We must make the output type is a library because we use Classlibrary-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Transaction.DAL\Transaction.DAL.csproj" />
	</ItemGroup>
</Project>